# Generated by Django 4.2.16 on 2026-03-15 05:00

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntraIDConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, max_length=200, verbose_name='Tenant ID')),
                ('client_id', models.CharField(blank=True, max_length=200, verbose_name='Application (Client) ID')),
                ('client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Client Secret')),
                ('allowed_domains', models.CharField(blank=True, help_text='Comma-separated list of allowed email domains. Leave blank to allow any Microsoft account.', max_length=500, verbose_name='Allowed Domains')),
                ('admin_group_id', models.CharField(blank=True, help_text='Azure AD group Object ID whose members receive Django admin access.', max_length=200, verbose_name='Admin Group Object ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enable Entra ID Authentication')),
            ],
            options={
                'verbose_name': 'Entra ID Configuration',
            },
        ),
        migrations.CreateModel(
            name='LDAPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_uri', models.CharField(default='ldap://ldap.example.com', max_length=500, verbose_name='LDAP Server URI')),
                ('bind_dn', models.CharField(blank=True, max_length=500, verbose_name='Bind DN')),
                ('bind_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Bind Password')),
                ('user_search_base', models.CharField(blank=True, max_length=500, verbose_name='User Search Base DN')),
                ('user_search_filter', models.CharField(default='(uid=%(user)s)', max_length=200, verbose_name='User Search Filter')),
                ('require_group', models.CharField(blank=True, help_text='DN of group required for login. Leave blank to allow all users.', max_length=500, verbose_name='Required Group DN')),
                ('admin_group', models.CharField(blank=True, help_text='DN of group whose members receive Django staff/superuser access.', max_length=500, verbose_name='Admin Group DN')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Use TLS (STARTTLS)')),
                ('skip_cert_verify', models.BooleanField(default=False, help_text='Disable TLS certificate verification (insecure — dev only).', verbose_name='Skip Certificate Verification')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enable LDAP Authentication')),
            ],
            options={
                'verbose_name': 'LDAP Configuration',
            },
        ),
    ]
