# Generated by Django 4.2.16 on 2026-03-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='ca_cert',
            field=models.TextField(blank=True, help_text='Paste the PEM certificate of the CA or LDAP server to trust. Leave blank to use system CAs.', verbose_name='CA Certificate (PEM)'),
        ),
    ]
