# Generated by Django 4.2.16 on 2026-03-15 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=100)),
                ('vmid', models.IntegerField(blank=True, null=True)),
                ('node', models.CharField(max_length=100)),
                ('upload_filename', models.CharField(max_length=500)),
                ('local_input_path', models.CharField(max_length=1000)),
                ('local_qcow2_path', models.CharField(blank=True, max_length=1000)),
                ('remote_qcow2_path', models.CharField(blank=True, max_length=1000)),
                ('stage', models.CharField(choices=[('QUEUED', 'Queued'), ('DETECTING', 'Detecting Format'), ('CONVERTING', 'Converting'), ('TRANSFERRING', 'Transferring'), ('CREATING_VM', 'Creating VM'), ('IMPORTING_DISK', 'Importing Disk'), ('CONFIGURING', 'Configuring'), ('STARTING', 'Starting'), ('CLEANUP', 'Cleanup'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('percent', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('vm_config_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
