# Generated by Django 4.2.16 on 2026-03-20 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LxcCreateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_name', models.CharField(max_length=100)),
                ('vmid', models.IntegerField(blank=True, null=True)),
                ('node', models.CharField(blank=True, max_length=100)),
                ('template', models.CharField(blank=True, max_length=500)),
                ('template_storage', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(choices=[('QUEUED', 'Queued'), ('DOWNLOADING', 'Downloading Template'), ('CREATING', 'Creating Container'), ('CONFIGURING', 'Configuring'), ('STARTING', 'Starting Container'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=30)),
                ('percent', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('ct_config_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lxc_create_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
