# Generated by Django 4.2.16 on 2026-03-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lxccreatejob',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lxccreatejob',
            name='task_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lxccreatejob',
            name='stage',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('DOWNLOADING', 'Downloading Template'), ('CREATING', 'Creating Container'), ('CONFIGURING', 'Configuring'), ('STARTING', 'Starting Container'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=30),
        ),
    ]
