# Generated by Django 4.2.16 on 2026-03-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_source',
            field=models.CharField(choices=[('local', 'Local'), ('ldap', 'LDAP'), ('entra', 'Entra ID')], default='local', max_length=20),
        ),
    ]
