# Generated by Django 4.2.16 on 2026-03-21 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exporter', '0002_exportjob_shutting_down_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxcPxImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_path', models.CharField(max_length=1000)),
                ('extract_dir', models.CharField(blank=True, max_length=1000)),
                ('manifest_json', models.TextField(default='{}')),
                ('ct_config_json', models.TextField(default='{}')),
                ('ct_name', models.CharField(blank=True, max_length=100)),
                ('vmid', models.IntegerField(blank=True, null=True)),
                ('node', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('QUEUED', 'Queued'), ('TRANSFERRING', 'Transferring Backup'), ('CREATING_CT', 'Restoring Container'), ('CONFIGURING', 'Configuring'), ('STARTING', 'Starting'), ('CLEANUP', 'Cleanup'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=30)),
                ('percent', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lxc_px_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LxcExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.IntegerField()),
                ('node', models.CharField(max_length=100)),
                ('ct_name', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('QUEUED', 'Queued'), ('READING_CONFIG', 'Reading Config'), ('EXPORTING', 'Exporting Container'), ('BUILDING_MANIFEST', 'Building Manifest'), ('PACKAGING', 'Packaging Archive'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=30)),
                ('percent', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('ct_config_json', models.TextField(default='{}')),
                ('output_path', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lxc_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
