"""Update the nginx WebSocket proxy config for VM console access.

Reads the Proxmox host/port from ProxmoxConfig and writes
/opt/proxmigrate/deploy/proxmox_ws.conf, then reloads nginx.

Called automatically by a post_save signal on ProxmoxConfig,
or manually: python manage.py update_nginx_ws
"""

import subprocess
import logging

from django.core.management.base import BaseCommand

logger = logging.getLogger(__name__)

WS_CONF_PATH = "/opt/proxmigrate/deploy/proxmox_ws.conf"

WS_CONF_TEMPLATE = """\
# Proxmox WebSocket proxy for VM console — auto-generated by ProxMigrate
location /vm-ws/ {{
    proxy_pass          https://{host}:{port}/api2/json/;
    proxy_http_version  1.1;
    proxy_set_header    Upgrade    $http_upgrade;
    proxy_set_header    Connection "upgrade";
    proxy_set_header    Host       {host}:{port};
    proxy_ssl_verify    off;
    proxy_read_timeout  600s;
    proxy_send_timeout  600s;
}}
"""


def write_ws_conf(host, port):
    content = WS_CONF_TEMPLATE.format(host=host, port=port)
    with open(WS_CONF_PATH, "w") as f:
        f.write(content)
    logger.info("update_nginx_ws: wrote %s (host=%s port=%s)", WS_CONF_PATH, host, port)


def reload_nginx():
    result = subprocess.run(["sudo", "nginx", "-s", "reload"], capture_output=True, text=True)
    if result.returncode != 0:
        logger.error("nginx reload failed: %s", result.stderr)
        return False
    logger.info("nginx reloaded successfully")
    return True


class Command(BaseCommand):
    help = "Update nginx WebSocket proxy config for VM console and reload nginx"

    def handle(self, *args, **options):
        from apps.wizard.models import ProxmoxConfig
        config = ProxmoxConfig.objects.first()
        if not config or not config.host:
            self.stderr.write("No ProxmoxConfig found or host not set — skipping")
            return

        write_ws_conf(config.host, config.api_port)
        if reload_nginx():
            self.stdout.write(self.style.SUCCESS(
                f"nginx WebSocket proxy updated: /vm-ws/ → {config.host}:{config.api_port}"
            ))
        else:
            self.stderr.write("nginx reload failed — check nginx logs")
