"""
Catalog loader for community scripts.

Reads the bundled JSON catalog (generated by apps/lxc/build_catalog.py)
and provides search, filter, and lookup helpers used by the community scripts views.

The check_for_updates() function makes a single lightweight GitHub API call to
detect when the upstream community-scripts repo has new commits.  The rebuild is
triggered by the user via a Celery task that shells out to the build script.
"""

import json
import logging
import os
import subprocess
import sys
from pathlib import Path

import requests

logger = logging.getLogger(__name__)

_DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
_SCRIPTS_PATH = os.path.join(_DATA_DIR, "community_scripts.json")
_CATEGORIES_PATH = os.path.join(_DATA_DIR, "community_categories.json")
_LAST_SHA_PATH = os.path.join(_DATA_DIR, ".last_commit_sha")

_GITHUB_COMMITS_URL = (
    "https://api.github.com/repos/community-scripts/ProxmoxVE/commits"
)

_catalog_cache = None
_catalog_mtime = 0
_categories_cache = None


# ── Catalog loading ─────────────────────────────────────────────────────

def get_catalog():
    """Load and cache the community scripts catalog.

    Checks the file's modification time so that when Celery rebuilds the
    JSON on disk, the web process picks up the new data on next request
    without needing a restart.
    """
    global _catalog_cache, _catalog_mtime, _categories_cache
    try:
        current_mtime = os.path.getmtime(_SCRIPTS_PATH)
    except OSError:
        current_mtime = 0

    if _catalog_cache is None or current_mtime != _catalog_mtime:
        try:
            with open(_SCRIPTS_PATH, encoding="utf-8") as f:
                _catalog_cache = json.load(f)
            _catalog_mtime = current_mtime
            # Also invalidate categories so they rebuild from new catalog
            _categories_cache = None
            logger.debug("Loaded community catalog: %d scripts (mtime=%s)",
                         len(_catalog_cache), current_mtime)
        except FileNotFoundError:
            logger.warning("Community catalog not found at %s", _SCRIPTS_PATH)
            _catalog_cache = []
        except json.JSONDecodeError as exc:
            logger.error("Failed to parse community catalog: %s", exc)
            _catalog_cache = []
    return _catalog_cache


def get_categories():
    """Load and cache the community categories list."""
    global _categories_cache
    if _categories_cache is None:
        try:
            with open(_CATEGORIES_PATH, encoding="utf-8") as f:
                _categories_cache = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            # Fall back to deriving categories from the catalog itself
            catalog = get_catalog()
            cats = set()
            for script in catalog:
                for cat in script.get("categories", []):
                    cats.add(cat)
            _categories_cache = [
                {"slug": cat.lower().replace(" ", "-").replace("&", ""),
                 "name": cat, "icon": "fa-solid fa-puzzle-piece"}
                for cat in sorted(cats)
            ]
    return _categories_cache


def invalidate_cache():
    """Clear the in-memory catalog and category caches so they reload from disk."""
    global _catalog_cache, _categories_cache
    _catalog_cache = None
    _categories_cache = None
    logger.info("Catalog cache invalidated")


def get_script(slug):
    """Find a script by slug, or return None."""
    for script in get_catalog():
        if script["slug"] == slug:
            return script
    return None


def search_catalog(query="", category=""):
    """
    Filter the catalog by search query and/or category slug.

    Returns a list of matching script dicts.
    """
    results = get_catalog()

    if category:
        cat_name = None
        for cat in get_categories():
            if cat["slug"] == category:
                cat_name = cat["name"]
                break
        if cat_name:
            results = [s for s in results if cat_name in s.get("categories", [])]

    if query:
        q = query.lower()
        results = [
            s for s in results
            if q in s.get("name", "").lower()
            or q in s.get("description", "").lower()
            or q in s.get("tags", "").lower()
            or q in s.get("slug", "").lower()
        ]

    return results


# ── Update checking ─────────────────────────────────────────────────────

def _get_stored_sha():
    """Read the commit SHA from the last successful catalog build."""
    try:
        with open(_LAST_SHA_PATH, encoding="utf-8") as f:
            return f.read().strip()
    except FileNotFoundError:
        return None


def _save_sha(sha):
    """Persist the latest commit SHA after a successful rebuild."""
    os.makedirs(os.path.dirname(_LAST_SHA_PATH), exist_ok=True)
    with open(_LAST_SHA_PATH, "w", encoding="utf-8") as f:
        f.write(sha)


def check_for_updates():
    """Check if the upstream community-scripts repo has new commits.

    Makes a single lightweight GitHub API call (unauthenticated, ~200 bytes).

    Returns:
        dict with keys:
            "update_available" (bool)
            "latest_sha" (str or None)
            "current_sha" (str or None)
            "error" (str or None)
    """
    current_sha = _get_stored_sha()

    try:
        resp = requests.get(
            _GITHUB_COMMITS_URL,
            params={"path": "ct", "per_page": "1"},
            timeout=10,
            headers={"Accept": "application/vnd.github.v3+json"},
        )
        resp.raise_for_status()

        commits = resp.json()
        if not commits:
            return {
                "update_available": False,
                "latest_sha": None,
                "current_sha": current_sha,
                "error": None,
            }

        latest_sha = commits[0]["sha"]

        return {
            "update_available": current_sha != latest_sha,
            "latest_sha": latest_sha,
            "current_sha": current_sha,
            "error": None,
        }

    except requests.RequestException as exc:
        logger.warning("GitHub update check failed: %s", exc)
        return {
            "update_available": False,
            "latest_sha": None,
            "current_sha": current_sha,
            "error": str(exc),
        }


def _find_build_script():
    """Locate build_catalog.py — lives alongside this module in apps/lxc/."""
    script_path = Path(__file__).resolve().parent / "build_catalog.py"
    if script_path.exists():
        return script_path
    return None


def can_refresh():
    """Return True if the build script is available for live catalog refresh."""
    return _find_build_script() is not None


def rebuild_catalog():
    """Run build_catalog.py to regenerate the catalog JSON files from GitHub.

    Returns:
        dict with keys:
            "success" (bool)
            "script_count" (int)
            "category_count" (int)
            "error" (str or None)
    """
    script_path = _find_build_script()
    if not script_path:
        return {
            "success": False,
            "script_count": 0,
            "category_count": 0,
            "error": "Build script not found. Update ProxOrchestrator to enable catalog refresh.",
        }

    try:
        result = subprocess.run(
            [sys.executable, str(script_path), "--output-dir", _DATA_DIR],
            capture_output=True,
            text=True,
            timeout=300,
        )

        if result.returncode != 0:
            logger.error("build_catalog.py failed: %s", result.stderr)
            return {
                "success": False,
                "script_count": 0,
                "category_count": 0,
                "error": f"Build script failed: {result.stderr[-500:]}",
            }

        # Save the latest SHA so the next update check knows we're current
        update_info = check_for_updates()
        if update_info.get("latest_sha"):
            _save_sha(update_info["latest_sha"])

        # Clear in-memory caches so the next request picks up new data
        invalidate_cache()

        # Count what we built
        catalog = get_catalog()
        categories = get_categories()

        logger.info("Catalog rebuilt: %d scripts, %d categories",
                     len(catalog), len(categories))

        return {
            "success": True,
            "script_count": len(catalog),
            "category_count": len(categories),
            "error": None,
        }

    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "script_count": 0,
            "category_count": 0,
            "error": "Catalog rebuild timed out after 5 minutes.",
        }
    except Exception as exc:
        logger.error("Catalog rebuild failed: %s", exc, exc_info=True)
        return {
            "success": False,
            "script_count": 0,
            "category_count": 0,
            "error": str(exc),
        }
