# Generated by Django 4.2.16 on 2026-04-18 02:19

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Cluster', max_length=100)),
                ('slug', models.SlugField(default='default', unique=True)),
                ('host', models.CharField(max_length=255)),
                ('ssh_port', models.IntegerField(default=22)),
                ('api_port', models.IntegerField(default=8006)),
                ('api_token_id', models.CharField(blank=True, max_length=255)),
                ('api_token_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('default_node', models.CharField(blank=True, max_length=100)),
                ('default_storage', models.CharField(blank=True, max_length=100)),
                ('default_bridge', models.CharField(blank=True, max_length=100)),
                ('proxmox_temp_dir', models.CharField(default='/var/tmp/proxorchestrator/', max_length=500)),
                ('virtio_iso', models.CharField(blank=True, default='', max_length=500)),
                ('upload_temp_dir', models.CharField(blank=True, default='', max_length=500)),
                ('default_cores', models.IntegerField(default=2)),
                ('default_memory_mb', models.IntegerField(default=2048)),
                ('vmid_min', models.IntegerField(default=100)),
                ('vmid_max', models.IntegerField(default=999)),
                ('is_configured', models.BooleanField(default=False)),
                ('wizard_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxmox Cluster',
            },
        ),
        migrations.CreateModel(
            name='ClusterNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(blank=True, max_length=255)),
                ('ssh_key_pushed', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='clusters.cluster')),
            ],
            options={
                'unique_together': {('cluster', 'name')},
            },
        ),
    ]
