# Generated by Django 4.2.16 on 2026-03-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_filename', models.CharField(max_length=500)),
                ('local_input_path', models.CharField(max_length=1000)),
                ('local_output_path', models.CharField(blank=True, max_length=1000)),
                ('detected_format', models.CharField(blank=True, max_length=50)),
                ('stage', models.CharField(choices=[('QUEUED', 'Queued'), ('DETECTING', 'Detecting Format'), ('CONVERTING', 'Converting'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('percent', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
